[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "uv-timer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
black = ">=25.1.0,<26"
pre-commit = ">=4.3.0,<5"

[pypi-dependencies]
uv_timer = { path = ".", editable = true }
